image: python:3.5

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip install flake8
  - mkdir -p /var/log/slashgif.com

django-test:
  stage: test
  script:
    - cp settings.ini.example settings.ini
    - python manage.py makemigrations
    - python manage.py migrate
    - flake8 --exclude migrations
