version: '3.9'

services:
  nginx:
    build: ./nginx
    image: shane-slashgif-site-nginx:latest
    env_file: settings.env
    deploy:
      mode: global
    volumes:
      - data_dir:/data
    depends_on:
      - app
    ports:
      - "80:80"

  app:
    build: ./app
    image: shane-slashgif-site-app:latest
    env_file: settings.env
    command: "gunicorn slashgif_site.wsgi:application -w 2 -b 0.0.0.0:9000"
    deploy:
      mode: global
    volumes:
      - data_dir:/data

volumes:
  data_dir:
